[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install --prefix netlify/functions/send-push"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/pitch"
  to = "/pitch.html"
  status = 200

[[redirects]]
  from = "/join"
  to = "/pitch.html"
  status = 200
